- scikits/cuda/linalg.py
- tests/test_linalg.py
This PR adds a `trace` function to the `linalg` module. As the name implies, this function simply calculates the trace (i.e., sum over diagonal elements) of a matrix.
Of course each user could easily implement this himself by using `pycuda.gpuarray.sum(linalg.diag(x_gpu))`*, so this is just a notational shortcut to save time / stay more in sync with numpy.
(* Apart from the fact that `linalg.diag` currently has a bug, for which I'll open a separate issue).
> ENH add linalg.trace operation

- scikits/cuda/linalg.py
- tests/test_linalg.py
Hi! 
``linalg.dot`` currently abstracts away a lot of the cumbersome setup for calling S/D/C/ZGEMM  (determining LDA, allocating outputs, ...) . However, it also has no options to specify ``alpha`` or ``beta``, even though that would sometimes be nice to have. For example it happens on occasion that I want to calculate
C += A * B
Which currently requires two steps (first calculating the dot product, then doing the addition), however I could get the same functionality for free using just a single GEMM call. ``linalg.add_dot`` thus wraps this functionality.  
(One could also simply add these options to the current ``linalg.dot`` function, but I thought that might be confusing, since then the function does more than simply calculate a dot product. But I'm happy to resubmit the PR with …
> Add linalg.dot_add

- scikits/cuda/cublas.py
- scikits/cuda/linalg.py
- tests/test_linalg.py
As discussed in #25 , this implements `linalg.dot_diag` using *dgmm. This brings some speedups. 
**IMPORTANT:** this PR breaks `linalg.pinv` for complex arguments, as that function relied upon the possibility to multiply a diagonal and a dense matrix of different types. I don't understand the `pinv` implementation enough to fix that, so I didn't!
> Implement linalg.dot_diag using dgmm

- scikits/cuda/linalg.py
- scikits/cuda/misc.py
Some python3 incompatibilities have snuck into scikits.cuda again. Mainly it was because functions in `linalg` didn't use the wrappers from `cula`, but rather used `cula._libcula` directly, which circumvents Py3 compatibility checks.
> Fix Python3 incompatibilities

- scikits/cuda/linalg.py
- tests/test_linalg.py
`scikits.cuda.linalg.det` calculates the determinant of a matrix, pretty much like `np.linalg.det` does.
Note: while writing this, I stumbled upon a weird bug in the testsuite: The tests refused to run because nosetests thought that names like "impl_test_trace" were actual tests. I don't know why this didn't work now (it always used to work previously) -- maybe I upgraded to a new version of nosetests without noticing? Anyway, that error is fixed with this commit as well. Sorry for not splitting it into a separate PR, I was too lazy ;)    (I also fixed a small potential bug in `linalg.inv` that I only noticed while implementing `det`).
> Add linalg.det to calculate matrix determinants

- docs/source/changes.rst
- docs/source/reference_misc.rst
- scikits/cuda/misc.py
- tests/test_misc.py
This PR adds `scikits.cuda.misc.min` (`max`, `argmin`, `argmax`) functions that compute the minimum/maximum and argmax/argmin along a given matrix axis, similar to `np.max`/`min`/`argmax`/`argmin`. 
The functions only works on real number types, because the semantics of  '>' and '<' (and consequently min/max) aren't clear to me for complex types. This is different from numpy, where min/max/argmax/argmin can be computed for complex matrices. 
I took the liberty of adding the things to CHANGES.txt and to the docs (I've noticed you always had to do that on your own after merging).
> Add functions for min/max and argmin/argmax along a matrix axis

- docs/source/changes.rst
- scikits/cuda/linalg.py
- tests/test_linalg.py
The default value for the `overwrite` parameter is now always False by default, as discussed in #110 .
> Consistent 'overwrite' default in skcuda.linalg

- scikits/cuda/magma.py
This PR adds wrappers for the gpu-versions of *GETRF, *GESV, *POSV, *POTRF, *POTRI and *SYMMETRIZE.
It also changes the error handling, so that each exception always contains the relevant error string + code, but no more specific exceptions are thrown for each magma error code (those codes seem to change each version anyhow, at least the ones that were present were outdated in magma 1.6).
> Added some new MAGMA functions to the wrapper

- scikits/cuda/magma.py
Small bugfix to make the `magma` module work in Python 3.
> Py3 compatibility fix for magma

- scikits/cuda/magma.py
This is another fix to make magma run under Python3. Sorry for discovering this so late.
> Another Py3 fix for magma.py

- scikits/cuda/magma.py
- scikits/cuda/misc.py
`skcuda.misc.argmax/argmin` don't work if you don't specify an axis (i.e., there is no implementation of calculating the global argmin/argmax yet). This PR throws an exception when a user tries to do it nevertheless.
> Warn when trying to compute skcuda.misc.argmax/argmin without axis

- skcuda/misc.py
- tests/test_misc.py
This adresses issue #123 , the broacastbehavior of the add/div/mult/_matvec now follow numpy's more closesly.
> Fix broadcasting behaviour of misc.add_matvec

- skcuda/misc.py
Hi, this adds four functions `misc.{add,subtract,multiply,divide}` that make the appropriate calls to mimic NumPy broadcasting for 0-2 dimensions. However,
- it doesn't do vector - matrix or vector / matrix because those kernels aren't implemented (I think)
- it doesn't support the `out` or `stream` options because the GPUArray ops don't
- to add a vector to the columns of a matrix, you have to do `linalg.add(m, v.reshape((-1, 1)))` which isn't so nice. GPUArray doesn't support `v[:,numpy.newaxis]` although it would be an easy change.
So, I can understand if you don't think this is the right way to go.
Examples:
```
a35 = numpy.random.uniform(0., 1., (3, 5))
a31 = numpy.random.uniform(0., 1., (3, 1))
a5 = numpy.random.uniform(0., 1., (5,))
a15 = numpy.random.uniform(0., 1., (1, 5))
g35 = …
```
> elementwise arithmetic with broadcasting up to 2 dimensions

- skcuda/cusolver.py
> platform.machine().endswith('64')
or 
> sys.platform.machine().endswith('64')
Does not work with Windows 10. Better is
> sys.maxsize > 2**32
See https://docs.python.org/2/library/platform.html
> sys.platform == 'win32':

- skcuda/misc.py
In the misc module,  opColVecToMat, I changed int32_t to int. int_32t was not defined in my CUDA-C environment and this is apparently common with Windows systems. As a result, any kernel calls originating from opColVecToMat would result in compilation errors.
> Changed int32_t to int for better Windows compatibility.

- skcuda/cufft.py
- skcuda/fft.py
- tests/test_fft.py
This change adds support for CUFFT's "extensible plan" API, in which
a handle is first created with cufftCreate and the actual plan made
later by cufftMakePlan*. This API is also used in the high-level Plan
object, since it allows parameters like compatibility mode to be set
before creating the plan (recommended by cufft docs).
Finally, support is added for caller-managed work area allocation. At
the low level, cufftSetAutoAllocation and cufftSetWorkArea are added. At
the high level, Plan() takes an auto_allocate argument, and adds a
Plan.set_work_area method.
This does not support the multi-GPU API, but it will be easier to add in
future because it is built on the extensible API. There are fundamental
issues with adding support, because for some pointer arguments there is
no way to know …
> Support and use cufft extensible plan API

- skcuda/linalg.py
There is `NotImplementError` instead of `NotImplementedError`
> Typo in linalg.py

- skcuda/utils.py
This fixes a problem on linux distros where objdump changes its output according to the locale (looking at you Debian).  This may lead to non-ascii characters in the output which then make the decode() fail.
> Set LANG to en when doing a callout.

- skcuda/linalg.py
cusolver requires the ldu and ldvt to be set correctly when using 'O' for jobu or jobvt
> Corrected ldu and ldvt when using jobu/jobv='O' in linalg.svd

- tests/test_misc.py
Running python3 setup.py test on Ubuntu 16.04, CUDA 8.0, python3.5, nose 1.3.7 also collects impl functions for some newly added tests currently. This change fixes these spurious warnings/failures by removing them from nose collection, by prepending function name with a _.
> Prepending impl test functions with _ so as not to be collected by nose

- demos/cusolver_demo_DnCheevjBatched.py
- demos/cusolver_demo_DnDsyevj.py
- demos/cusolver_demo_DnDsyevjBatched.py
- demos/cusolver_demo_DnZheevj.py
- skcuda/cudart.py
- skcuda/cusolver.py
In addition to the wrappers, I changed cudart._cudart_version to use cudaRuntimeVersion instead of cudaDriverVersion. Here is an example that cusolver cannot be loaded correctly when using driver version:
I have latest CUDA driver that correspond to driver version 9.0, but using cuda toolkit 8.0. Using driver version as _cudart_version, cusolver.py cannot find functions that require 9.0, since it's loading 8.0 libraries.
> Adding a few more wrappers for symmetric matrix eigen decomposition routines

- skcuda/cusolver.py
Python 3 linalg cusolver QR tests were failing because the argtypes are wrong. Why this didn't fail on Python 2, I have no idea.
```
File "/home/sclarkson/skcuda/skcuda/cusolver.py", line 1229, in cusolverDnDgeqrf_bufferSize
lda, ctypes.byref(lwork))
ctypes.ArgumentError: argument 3: <class 'TypeError'>: wrong type
```
Note that the tests will still fail after this PR, but now because
```
Boost.Python.ArgumentError: Python argument types in
Memcpy2D.set_src_device(Memcpy2D, numpy.int64)
did not match C++ signature:
set_src_device(pycuda::memcpy_2d {lvalue}, unsigned long long)
```
Reverting the changes from #131 will fix this, but that seemed like a separate PR.
> fix *geqrf cytpe arguments

- skcuda/__init__.py
I've seen failures like
```
CompileError: nvcc compilation of /tmp/tmplopoyu/kernel.cu failed
[command: nvcc --cubin -I skcuda/include -arch sm_61 -I/usr/lib/python2.7/dist-packages/pycuda/cuda kernel.cu]
[stderr:
kernel.cu:5:36: fatal error: cuSpecialFuncs.h: No such file or directory
compilation terminated.
]
```
Using an absolute import seems more robust.
> switch to absolute import path

- skcuda/cublasxt.py
- skcuda/linalg.py
- skcuda/pcula.py
```
======================================================================
ERROR: test_qr_reduced_cusolver_complex128 (test_linalg.test_linalg)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/sclarkson/scikit-cuda/tests/test_linalg.py", line 1479, in test_qr_reduced_cusolver_complex128
self._impl_test_qr_reduced(np.complex128, 'cusolver')
File "/home/sclarkson/scikit-cuda/tests/test_linalg.py", line 1451, in _impl_test_qr_reduced
assert_allclose(a, np.dot(q_gpu.get(), r_gpu.get()), atol=1e-4)
File "/usr/lib/python3/dist-packages/pycuda/gpuarray.py", line 271, in get
_memcpy_discontig(ary, self, async=async, stream=stream)
File "/usr/lib/python3/dist-packages/pycuda/gpuarray.py", line 1265, in _memcpy_discontig …
```
> Fix QR tests on python 3 (revert #131 workaround)

- skcuda/misc.py
skcuda/misc.py:637: DeprecationWarning: `np.typeDict` is a deprecated alias for `np.sctypeDict`.
> Remove deprecation warning
