- scikits/cuda/linalg.py
There is currently a bug in ``linalg.dot_diag`` if ``overwrite=False``. This is fixed with this PR.
> Fix missing variable in dot_diag

- scikits/cuda/linalg.py
- tests/test_linalg.py
This PR makes it possible to put strided/sliced arrays into linalg.dot. I.e., it allows stuff like:
linalg.dot(a_gpu[:, 4:10], b_gpu[:, 2:8], 'n', 't', out= c_gpu[:, 1:7])
This will now work fine, as long as the slicing is over the axis closest in memory (i.e., columns for C-order arrays). The same technique could probably applied to the other methods in ``linalg``, i.e., to allow slicing for SVD or Cholesky decomposition, but my immediate interest was for ``linalg.dot``/``add_dot`` only. If there is interest, I could add it to the other methods as well, though.
> Allow strided arrays in linalg.dot and linalg.add_dot

- scikits/cuda/misc.py
- tests/test_misc.py
This PR adds functions similar to  `misc.add_matvec`, but who do division/multiplication instead of addition.
> Generalize add_matvec to ther operations as well

- scikits/cuda/integrate.py
- scikits/cuda/linalg.py
- scikits/cuda/misc.py
Currently, `scikits.cuda` contains some functions that call SourceModule to compile code directly (e.g. `linalg.tril` or `linalg.diag`). I've noticed today that this is very bad for performance if you use these functions more often: on every call of these functions, the whole source code will be recompiled. i.e., if you call `linalg.diag` 100x in a loop, you will go throught the whole nvcc-compile process for the kernel 100x. This makes those functions pretty much un-usable within inner loops.
I've solved this using the same pattern that is used in PyCUDA itself to deal with this: All functions using `SourceModule` are wrapped, and use the `@context_dependent_memoize` decorator to memoizes the compilation process. This way, each `SourceModule` is only compiled once and the result is …
> Memoize SourceModule calls

- scikits/cuda/linalg.py
This commit memoizes some more kernels in `skcuda.linalg`, otherwise they get recompiled on every call of the function.
> Memoized some more kernels in skcuda.linalg

- skcuda/cula.py
- skcuda/linalg.py
- tests/test_linalg.py
> CULA QR Decomposition

- skcuda/cusolver.py
This PR fixes an error when trying to import the cusolver module.
> Fix cusolver import error

- skcuda/linalg.py
- tests/test_linalg.py
Generate a Vandermonde matrix.
> CUDA Vandermonde Matrix

- skcuda/info.py
- skcuda/rlinalg.py
- tests/test_rlinalg.py
Works fine... But I will add any-when later a wrap for the cuRAND library, to have access to better random number generators.
> Randomized Singular Value Decomposition (rsvd)

- skcuda/linalg.py
- skcuda/rlinalg.py
- tests/test_linalg.py
- tests/test_rlinalg.py
And some cleanups and fixes....
> Randomized Dynamic Mode Decomposition

- docs/source/reference_cufft.rst
- skcuda/cufft.py
These functions return an estimate of the size of working array that will be allocated when constructing an FFT plan.
> Wrap cufft size estimation functions

- demos/diag_demo.py
- demos/dot_demo.py
- demos/fft2d_batch_demo.py
- demos/fft2d_demo.py
- demos/fft_batch_demo.py
- demos/fft_demo.py
- demos/indexing_2d_demo.py
- demos/indexing_3d_demo.py
- demos/indexing_4d_demo.py
- demos/mdot_demo.py
- demos/pinv_demo.py
- demos/svd_demo.py
- demos/transpose_demo.py
- demos/tril_demo.py
I updated the demos to be python2 and 3 compatible.
Since I don't have CULA I couldn't fully test `pinv_demo.py` and `svd_demo.py` but they give no syntaxerror and since the changes are minimal it shouldn't be a problem.
I added some pep8 fixes with the help of autopep8 (I checked manually when committing and of course ran the scripts).
> Update demos for python3

- skcuda/misc.py
The mult_matvec and div_matvec documentation described addition, not multiplication / division.
> Fix mult_matvec, div_matvec documentation.

- skcuda/magma.py
magma_uplo_const() expect a bytes and plain strings are unicode on python 3.
> Fix magma init for python 3.

- skcuda/cublas.py
tested in cuda 9.1
i'm not sure about the version check code
> [#243] add cublas<T>getrfBatched, cublas<T>getriBatched for C and Z

- skcuda/cublas.py
sorry,there are some mistakes i made.
> [#243] ....fix mistake of cublas<T>getrfBatched

- skcuda/integrate.py
- tests/test_integrate.py
In the hope that this is also useful for others, an additional numerical integration method, namely composite Simpson's rule, was implemented in similar fashion to skcuda.integrate.trapz
> added simpson's rule for numerical integration on gpu

- demos/magma_all_geev_demo.py
- skcuda/magma.py
I have fixed a few interface for geev. I have also included a new demo/test for the magma eigenvalue routines.
> Fixing magma eigensolver wrappers: sgeev, dgeev, cgeev, zgeev

- skcuda/cudart.py
Stable release of CUDA 10.2 was on Nov 20, 2019
> Added CUDA 10.2 to cudart.py version list

- skcuda/cublas.py
The `ldb` parameter should refer to the `B` matrix.
> Fix typo in _GEAM doc.
